#!/bin/sh
chsh -s /usr/bin/fish

sudo rm -fr /var/service/agetty-tty3
sudo rm -fr /var/service/agetty-tty4
sudo rm -fr /var/service/agetty-tty5
sudo rm -fr /var/service/agetty-tty6

sudo xbps-install -Suvy && sudo xbps-install -Suvy
sudo xbps-install -Sv fish-shell htop xorg-minimal xinit xf86-video-intel neofetch nano make build-essential curl font-sourcecodepro scrot autoconf automake gtk+3-devel gnome-themes-standard gtk-engine-murrine noto-fonts-ttf tar bzip2 xz zip unzip p7zip alsa-utils alsa-tools xtools python-pip void-repo-multilib

curl -L https://get.oh-my.fish | fish
omf install pure

pip install setuptools wheel ps_mem

cd /dwm-6.1/
sudo make clean install
cd ../st/
sudo make clean install
cd

git clone https://github.com/horst3180/arc-theme --depth 1 && cd arc-theme && ./autogen.sh --prefix=/usr
