#!/bin/sh
sudo rm -fr /var/service/agetty-tty3
sudo rm -fr /var/service/agetty-tty4
sudo rm -fr /var/service/agetty-tty5
sudo rm -fr /var/service/agetty-tty6

sudo xbps-install -Suvy && sudo xbps-install -Suvy
sudo xbps-install -Suvy vim fish-shell htop xorg-minimal xinit xf86-video-intel neofetch make base-devel curl font-sourcecodepro scrot autoconf automake gtk+3-devel gnome-themes-standard gtk-engine-murrine noto-fonts-ttf tar bzip2 xz zip unzip p7zip alsa-utils alsa-tools xtools ranger python python3 python-pip dmenu irssi w3m w3m-img libexif-devel imlib2-devel giflib-devel xorg-fonts compton xset xsetroot hsetroot xrandr setxkbmap acpi irssi-perl xtools lxappearance udiskie firefox font-symbola courier-unicode

sudo pip install setuptools wheel ps_mem
cp -v .vimrc compton.conf run-dwm.sh .Xresources ~/
mkdir ~/.irssi
cp -vr irssi/* ~/.irssi

cd ./dwm/
sudo make clean install
cd ../st/
sudo make clean install
cd ../sxiv-24/
make
sudo make install
cd

rm -rf ./arc-theme/
git clone https://github.com/horst3180/arc-theme --depth 1 && cd arc-theme && ./autogen.sh --prefix=/usr

chsh -s /usr/bin/fish
curl -L https://get.oh-my.fish | fish
omf install pure
git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell

